plugins {
    id 'com.android.application'
}

android {
    namespace 'org.alberto97.aodtoggle'
    compileSdk 37

    defaultConfig {
        applicationId "org.alberto97.aodtoggle"
        minSdkVersion 26
        targetSdkVersion 37
        versionCode 5
        versionName "1.1.1"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:6.1'

    def shizuku_version = "13.1.5"
    implementation "dev.rikka.shizuku:api:$shizuku_version"
    implementation "dev.rikka.shizuku:provider:$shizuku_version"

    compileOnly "dev.rikka.hidden:stub:4.4.0"
}
